# Generated by Django 5.0.14 on 2025-09-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=4.5, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='reviews',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
